AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
  InputBucket:
    Type: String
  NotifyLambda:
    Type: String
Resources:

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${EnvironmentName}-Notification-Event"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref InputBucket
      Targets:
        - Arn: !Ref NotifyLambda
          Id: LambdaTarget
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs: 
  EventRuleArn:
    Value: !GetAtt EventRule.Arn

  




